nttcom/OsecT

- osect_sensor/Infrastructure/edge_cron/Dockerfile
- osect_sensor/Infrastructure/edge_tcpdump/Dockerfile
hadolintによるエラーのうち
- apt-get
- pip
- cd
に関わるものだけ修正
> 各Dockerfileに対するhadolintのエラー対処

- osect_sensor/Infrastructure/edge_cron/Dockerfile
- osect_sensor/README.md
Dockerfileにlibfixbufとyafのwgetを追加。
README.mdで「3 YAFのダウンロード」の項目を削除＋章番号を振り直す
> fix Dockerfile && README.md

- osect_sensor/Infrastructure/edge_cron/Dockerfile
> update zeek packages

- osect_sensor/Application/edge_cron/cron/management/commands/pcap_to_log_to_server.py
- osect_sensor/Application/edge_cron/cron/management/commands/send_version.py
> verify certificates

- osect_sensor/Application/edge_cron/cron/management/commands/send_version.py
- osect_sensor/Infrastructure/edge_cron/work/ot_tools/suricata_update.sh
更新失敗時やシグネチャ最新時にもコアにバージョンを送るよう修正
> 更新失敗時やシグネチャ最新時にもコアに送るよう修正

- osect_sensor/Infrastructure/edge_cron/Dockerfile
- osect_sensor/Infrastructure/edge_cron/work/ot_tools/bacnet.sh
- osect_sensor/Infrastructure/edge_cron/work/ot_tools/bro.sh
- osect_sensor/Infrastructure/edge_cron/work/ot_tools/ot_cron.sh
- osect_sensor/Infrastructure/edge_cron/work/ot_tools/suricata_update.sh
- osect_sensor/Infrastructure/edge_cron/work/ot_tools/yaf.sh
ソースからではなく、`apt-get`でインストールする方法に変更
> Suricataのインストール方法を変更

- osect_sensor/Infrastructure/edge_cron/work/requirements.txt
- osect_sensor/Infrastructure/edge_tcpdump/work/requirements.txt
Django==3.2.12　→　Django==3.2.13　へバージョンアップ
> #39 djangoの脆弱性対応

- osect_sensor/Infrastructure/edge_cron/work/requirements.txt
- osect_sensor/Infrastructure/edge_tcpdump/work/requirements.txt
> #275 ライブラリ・パッケージの脆弱性対応のためコンテナ資材を修正

- osect_sensor/Infrastructure/edge_cron/work/ot_tools/broscript/arp.zeek
https://gikai.slack.com/archives/C0161S830SX/p1681084547153559
上記の問題対応
> arp.zeekの修正

- osect_sensor/conf/crontab
> crontab内のランダム化処理の不具合修正

- osect_sensor/Infrastructure/edge_cron/Dockerfile
BACnetは商用ではないなので、BACnetに関わるコードをコメントアウトにしました。
buildが通ることのテスト：
> seperate bacnet function from main branch

- README.md
(OTセキュリティリスク可視化サービス OsecT、リニューアルしました)[https://engineers.ntt.com/entry/2023/08/31/100633]をREADMEに追加
> 技術ブログの記事を追加

- osect_sensor/Infrastructure/edge_cron/work/ot_tools/bro.sh
issue #142 
bacnet branchも同じようにログが削除できないバグを修正しました。
> fix bug when deleting log in bacnet branch

- osect_sensor/Infrastructure/edge_cron/Dockerfile
modbusのログがOsecTコア側で読み込めるために、`zkg install icsnpp-modbus --version 03de54df8b0a8c1e6264876167f80dccae74902a --force --skiptest \`で icsnpp-modbusをinstallします。
テストして、ログの形式はあっています。
root@sensor:/usr/local/zeek/logs/2023-11-15# cat modbus_detailed.14:24:37-14:25:00.log 
```
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   modbus_detailed
#open   2023-11-15-14-24-37
#fields ts      uid     id.orig_h       id.orig_p       id.resp_h       id.resp_p       unit_id func    network_directionaddress  quantity        values
#types  time    string  addr    port    addr    port    count   string  string  count   count   string
1700025877.459336       CalSmx2YYuKwMXMQjl      127.0.0.1       47785   127.0.0.1       502     4       READ_COILS      request   1       1       - …
```
> Update Dockerfile to use a former version of modbus

- README.md
OsecTセンサーのGitHubのREADMEを更新：
OT環境向けセキュリティ対策「OsecT」
既存システムに影響を与えず
ネットワーク可視化・セキュリティリスク検知
https://www.newww-media.co.jp/backnumber/202401/202401p26.pdf
> Add nikkei interview to README.md

- README.md
2023年12月22日の情報ネットワーク研究会（IN研究会）で発表した「制御システムネットワークの実態とセキュリティ課題」の講演資料 と
鄭さんの技術ブログ記事
をreadmeに追加しました。
> 紹介記事・関連記事を追加

- README.md
> name change in read me

- osect_sensor/README_en.md
- osect_sensor/SPECIFICATION.md
- osect_sensor/SPECIFICATION_en.md
close #153 
There is one question in the comment, please confirm it before approval.
> add English version readme and specifications

- osect_sensor/README_en.md
'not need' should be 'no need'.
> correct word in README_en.md

- osect_sensor/Infrastructure/edge_cron/Dockerfile
> Suricataをバージョン指定でインストールできるように修正

- osect_sensor/Infrastructure/edge_cron/Dockerfile
- 最新バージョン確認
- エラーなくbuildできることを確認
```
Step 36/36 : RUN printenv | grep -e https_proxy -e HTTPS_PROXY -e http_proxy -e HTTP_PROXY -e no_proxy -e NO_PROXY| awk '{print "export " $1}' > /opt/ot_tools/proxy_env.txt     && mv supervisord.conf /etc/supervisor/conf.d/
---> Running in 787fc4e3d80d
---> Removed intermediate container 787fc4e3d80d
---> b74076e435cb
Successfully built b74076e435cb
Successfully tagged cron:revxxx
2024/02/13_06:29:35 instance-admin:~/tei_workspace/osect_sensor
[osect_so@ osect_sensor](unified-it-o-63054301)$
```
> DockerFileのSuricataのバージョンアップ

- osect_sensor/conf/suricata.yaml
close #179
suricata.yamlのHOME_NETの設定をプライベートIPアドレスの範囲（10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16）に変更
> #179 suricata.yamlのHOME_NETの設定を変更

- README.md
> READMEにプレスリリースと受賞を追加

- README.md
> Update README.md for 社外発表

- README.md
> update メディア掲載 in README
